apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: annotator
  labels:
    operator: annotator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        operator: annotator
    spec:
      containers:
       - name: annotator
         image: rossf7/annotator:0.0.1
         imagePullPolicy: IfNotPresent
